SELECT a.AUTHOR_ID, a.AUTHOR_NAME, b.CATEGORY, sum(b.PRICE*s.SALES) AS TOTAL_SALES
FROM BOOK b, AUTHOR a, BOOK_SALES s
WHERE b.BOOK_ID=s.BOOK_ID AND b.AUTHOR_ID=a.AUTHOR_ID AND s.SALES_DATE LIKE "2022-01-%"
GROUP BY a.AUTHOR_ID, b.CATEGORY
ORDER BY a.AUTHOR_ID ASC, b.CATEGORY DESC;