/*
- given:
    - 대여 중인 자동차들의 정보를 담은 CAR_RENTAL_COMPANY_CAR
    - 자동차 대여 기록 정보를 담은 CAR_RENTAL_COMPANY_RENTAL_HISTORY
    - 자동차 종류 별 대여 기간 종류 별 할인 정책 정보를 담은 CAR_RENTAL_COMPANY_DISCOUNT_PLAN
- return: 종류가 '트럭'인 자동차의 대여 기록에 대해서 대여 기록 별로 대여 금액(컬럼명: FEE)을 구하여, 대여 기록 ID와 대여 금액을 출력
    - 일일 대여 금액 26,000원에서 5% 할인율을 적용하고 7일을 곱하면 총 대여 금액은 172,900원
    - 대여 금액을 기준으로 내림차순 정렬 및 대여 기록 ID를 기준으로 내림차순 정렬
    - FEE의 경우 예시처럼 정수부분만 출력
*/

# SELECT H.HISTORY_ID,
#     CEIL((100 - COALESCE((SELECT P.DISCOUNT_RATE
#     FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
#     WHERE P.CAR_TYPE = '트럭'
#         AND TIMESTAMPDIFF(DAY, H.START_DATE, H.END_DATE) + 1 
#             >= CAST(SUBSTRING(P.DURATION_TYPE, 1, LOCATE('일', P.DURATION_TYPE) - 1) AS UNSIGNED)
#     ORDER BY CAST(SUBSTRING(P.DURATION_TYPE, 1, LOCATE('일', P.DURATION_TYPE) - 1) AS UNSIGNED) DESC
#     LIMIT 1
#     ), 0)) / 100 * C.DAILY_FEE * TIMESTAMPDIFF(DAY, H.START_DATE, H.END_DATE) + 1) AS FEE
# FROM CAR_RENTAL_COMPANY_CAR C, CAR_RENTAL_COMPANY_RENTAL_HISTORY H
# WHERE C.CAR_ID = H.CAR_ID AND C.CAR_TYPE = '트럭'
# ORDER BY FEE DESC, H.HISTORY_ID DESC;

SELECT H.HISTORY_ID,
    CEIL((100 - COALESCE(
        (SELECT P.DISCOUNT_RATE
         FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
         WHERE P.CAR_TYPE = '트럭'
             AND TIMESTAMPDIFF(DAY, H.START_DATE, H.END_DATE) + 1 
                 >= CAST(SUBSTRING(P.DURATION_TYPE, 1, LOCATE('일', P.DURATION_TYPE) - 1) AS UNSIGNED)
         ORDER BY CAST(SUBSTRING(P.DURATION_TYPE, 1, LOCATE('일', P.DURATION_TYPE) - 1) AS UNSIGNED) DESC
         LIMIT 1
        ), 0)) / 100 * C.DAILY_FEE * (TIMESTAMPDIFF(DAY, H.START_DATE, H.END_DATE) + 1)) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C, CAR_RENTAL_COMPANY_RENTAL_HISTORY H
WHERE C.CAR_ID = H.CAR_ID AND C.CAR_TYPE = '트럭'
ORDER BY FEE DESC, H.HISTORY_ID DESC;

# SELECT *
# FROM CAR_RENTAL_COMPANY_CAR C, CAR_RENTAL_COMPANY_RENTAL_HISTORY H
# WHERE C.CAR_ID = H.CAR_ID AND C.CAR_TYPE = '트럭';

# SELECT SUBSTRING(DURATION_TYPE, 1, LOCATE('일', DURATION_TYPE) - 1) AS DURATION, DISCOUNT_RATE
# FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
# WHERE CAR_TYPE = '트럭'
# ORDER BY CAST(DURATION AS UNSIGNED) DESC;